"use client";

import type { Contact, Message } from "@/lib/types";
import { cn } from "@/lib/utils";
import { format } from "date-fns";
import { Bot } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";


interface MessageBubbleProps {
  message: Message;
  contact: Contact;
}

export function MessageBubble({ message, contact }: MessageBubbleProps) {
  const isFromMe = message.senderId === "me";

  return (
    <div
      className={cn(
        "flex max-w-[75%] items-end gap-2",
        isFromMe ? "ml-auto flex-row-reverse" : "mr-auto"
      )}
    >
      <div
        className={cn(
          "relative rounded-lg px-4 py-2",
          isFromMe
            ? "rounded-br-none bg-primary text-primary-foreground"
            : "rounded-bl-none bg-secondary text-secondary-foreground"
        )}
      >
        {message.content}
        
        {message.isAiResponse && (
           <TooltipProvider>
            <Tooltip>
              <TooltipTrigger asChild>
                <Bot className="absolute -bottom-2 -right-2 h-4 w-4 text-accent bg-background rounded-full p-0.5"/>
              </TooltipTrigger>
              <TooltipContent>
                <p>This message was generated by AI.</p>
              </TooltipContent>
            </Tooltip>
          </TooltipProvider>
        )}
      </div>
      <span className="text-xs text-muted-foreground pb-1">
        {format(message.timestamp, "p")}
      </span>
    </div>
  );
}
